/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cubed.gltf --transform
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cubed-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.92, 0.05]} rotation={[0, -0.79, 0]} scale={0.16}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.mesh_0_1.geometry}
          material={materials.Material}
        />
        <mesh geometry={nodes.mesh_0_2.geometry} material={materials.Greeen} />
        <mesh geometry={nodes.mesh_0_3.geometry} material={materials.Red} />
        <mesh geometry={nodes.mesh_0_4.geometry} material={materials.Yellow} />
        <mesh geometry={nodes.mesh_0_5.geometry} material={materials.White} />
      </group>
      <group
        position={[0.28, 0.06, -0.31]}
        rotation={[1.23, -0.25, 0.06]}
        scale={2.68}
      >
        <mesh
          geometry={nodes.mesh_1.geometry}
          material={materials['glossy putih.011']}
        />
        <mesh
          geometry={nodes.mesh_1_1.geometry}
          material={materials['glossy fb']}
        />
      </group>
      <group
        position={[0.28, 0.06, -0.31]}
        rotation={[Math.PI / 2, 0, 0.65]}
        scale={0.14}
      >
        <mesh
          geometry={nodes.mesh_2.geometry}
          material={materials['glossy behance.001']}
        />
        <mesh
          geometry={nodes.mesh_2_1.geometry}
          material={materials['GLOSSY YT.002']}
        />
        <mesh
          geometry={nodes.mesh_2_2.geometry}
          material={materials['glossy putih.011']}
        />
      </group>
      <group
        position={[0.28, 0.06, -0.31]}
        rotation={[1.13, -0.32, 0.67]}
        scale={0.1}
      >
        <mesh
          geometry={nodes.mesh_3.geometry}
          material={materials['glossy putih.011']}
        />
        <mesh
          geometry={nodes.mesh_3_1.geometry}
          material={materials['google 3 GLOS.001']}
        />
        <mesh
          geometry={nodes.mesh_3_2.geometry}
          material={materials['google 4 GLOS.001']}
        />
        <mesh
          geometry={nodes.mesh_3_3.geometry}
          material={materials['google2 GLOS.001']}
        />
        <mesh
          geometry={nodes.mesh_3_4.geometry}
          material={materials['google 1 GLOS.001']}
        />
      </group>
      <group
        position={[0.28, 0.06, -0.31]}
        rotation={[1.13, -0.75, 0.62]}
        scale={0.7}
      >
        <mesh
          geometry={nodes.mesh_4.geometry}
          material={materials['glossy putih.011']}
        />
        <mesh
          geometry={nodes.mesh_4_1.geometry}
          material={materials['glossy snapshat.001']}
        />
      </group>
      <group
        position={[0.28, 0.06, -0.31]}
        rotation={[1.11, -0.24, -0.11]}
        scale={0.6}
      >
        <mesh
          geometry={nodes.mesh_5.geometry}
          material={materials['tiktok 2 GLOSS.001']}
        />
        <mesh
          geometry={nodes.mesh_5_1.geometry}
          material={materials['glossy putih.011']}
        />
        <mesh
          geometry={nodes.mesh_5_2.geometry}
          material={materials['tiktok 3 GLOSS.001']}
        />
        <mesh
          geometry={nodes.mesh_5_3.geometry}
          material={materials['glossy tiktok.001']}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder043.geometry}
        material={materials['glossy putih.011']}
        position={[-0.06, 0.39, 0.21]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.16}
      />
      <mesh
        geometry={nodes.Cylinder042.geometry}
        material={materials['glossy ig']}
        position={[-0.06, 0.39, 0.21]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        geometry={nodes.Cylinder023.geometry}
        material={materials['glossy ig']}
        position={[-0.06, 0.39, 0.21]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.2}
      />
      <mesh
        geometry={nodes.Cylinder037.geometry}
        material={materials['glossy putih.011']}
        position={[0.03, 0.15, 0.45]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Cylinder036.geometry}
        material={materials['glossy linkedin']}
        position={[0.03, 0.2, 0.45]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.13}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials['glossy linkedin']}
        position={[0.03, 0.15, 0.45]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.13}
      />
      <mesh
        geometry={nodes.Curve009.geometry}
        material={materials['default']}
        position={[0.25, 0.29, 0.21]}
        rotation={[Math.PI / 2, 0, -0.61]}
        scale={1.83}
      />
      <mesh
        geometry={nodes.Curve007.geometry}
        material={materials['default']}
        position={[0.25, 0.29, 0.21]}
        rotation={[Math.PI / 2, 0, -0.61]}
        scale={1.83}
      />
      <mesh
        geometry={nodes.Curve003.geometry}
        material={materials['glossy ig']}
        position={[0.25, 0.29, 0.21]}
        rotation={[Math.PI / 2, 0, -0.61]}
        scale={1.83}
      />
      <mesh
        geometry={nodes.Stylized_Spline.geometry}
        material={materials.Material}
        position={[-0.01, 0.5, 0.07]}
        rotation={[0, -0.79, 0]}
        scale={0.39}
      />
      <mesh
        geometry={nodes.Glass.geometry}
        material={materials.Glass}
        position={[0, 0, -0.55]}
        rotation={[0, Math.PI / 4, 0]}
        scale={0.88}
      />
    </group>
  );
}

useGLTF.preload('/cubed-transformed.glb');
